### ISSUE TITLE
Errno 14 Bad address on MSYS2

### ISSUE THREAD

**Issue by chwba** [AtomLinter/linter-pylama#101]
[Errno 14] Bad address: '../../../../../../../C:\\Users\\Username\\AppData\\Local\\Temp\\atom-linter_6424nvtSzC3nmArH\\Load_saved_model.py' [undefined]

**Comment by Arcanemagus** [comment]
That error looks to be coming from PyLama itself from the little bit of information you have provided. Does it work in the terminal?

**Comment by chwba** [comment]
i switched to python-ide it got too time consuming, sry
