### ISSUE TITLE
No way to customize commonly used linter options

### ISSUE THREAD

**Issue by viernullvier** [AtomLinter/linter-pylama#11]
It would be nice if there was an easy way to set some specific linter options, namely maximum line length for pep8 and maximum complexity for McCabe.

As of now, I'm changing these options directly in the corresponding source files, but there has to be a better way. Maybe an (optional) path to a [global config file](https://github.com/klen/pylama#configuration-files)?

**Comment by dingus9** [comment]
Would just need to pass -o /path/to/config/file.ini
