### ISSUE TITLE
Support for py3

### ISSUE THREAD

**Issue by alexjurkiewicz** [AtomLinter/linter-pylama#17]
Hi, it seems Python 3 syntax isn't supported by default when I install this module:
![screen shot 2015-11-12 at 10 29 36 am](https://cloud.githubusercontent.com/assets/379509/11106192/4eedef9a-8928-11e5-98e1-16f40a1f0ae0.png)

Is there some way to get py3 support?

Some of my projects are py2 and some are py3, so being able to flip between them would be nice.

**Comment by Arcanemagus** [comment]
This would be an issue with [pylama](https://github.com/klen/pylama), not `linter-pylama` as this package just returns the results from that. Perhaps you have multiple versions for py2 vs. py3 and are calling the wrong one?

**Comment by alexjurkiewicz** [comment]
Sorry, I thought this package came with a bundled pylama that it uses?

**Comment by Arcanemagus** [comment]
Although that is true, the embedded versions are pylama 7.0.4 (latest is 7.0.6) and pylama-pylint 2.1.1 (latest). It doesn't look like any of the changes between 7.0.4 and 7.0.6 would affect this.

It looks like that error is being forwarded on from pylint so I would probably check there.

**Comment by Arcanemagus** [comment]
From what I remember these linter's change their used rules based on the python they are run under, are you sure you are running this in an environment that is using Python 3?

**Comment by alexjurkiewicz** [comment]
I'm running on OSX, so the system default 'python' is 2.x. There's a
'python3' available though. Is there some way to have this plugin use
python3 if it's available? From what I understand (not much), pylama
running under Python 3 will work for both py2 & py3 code...

**Comment by Arcanemagus** [comment]
You would probably need to launch Atom from within a py3 virtualenv, let me know how that goes.

**Comment by gmist** [comment]
pylama fully supports py3
<img width="331" alt="screen shot 2015-11-12 at 12 46 59" src="https://cloud.githubusercontent.com/assets/47926/11115584/92e994fa-893d-11e5-8b48-049e71811619.png">


but uses the system default python. As @Arcanemagus wrote above you can launch Atom (or pylama directly) from virtualenv.

Step 1. Check system python version
``` shell
$ python -V
Python 2.7.10
```

Step 2. Find  the full path of python3
``` shell
$ which python3
/usr/local/bin/python3
```

Step 3. Setup a new virtualenv with python3
``` shell
$ cd <path_to_project>
$ mkvirtualenv --python=/usr/local/bin/python3 project_name
```

Step 4. Check virtualenv python version and run Atom
``` shell
$ python -V
Python 3.5.0
$ atom .
```

Later you can switch between environments with ```workon``` command.
