### ISSUE TITLE
Contradicting PEP257 warnings

### ISSUE THREAD

**Issue by bemeurer** [AtomLinter/linter-pylama#25]
I keep getting a
 `D211 No blank lines allowed before class docstring (found 1) [pep257]at line 63 col 1 in server.py`
Warning, but then when I remove the blank line I get
`D203 1 blank line required before class docstring (found 0) [pep257]at line 63 col 1 in server.py`
The code looks like this:
```python
class Asyncable(object):
    """TODO: Docstring."""

    def readable(self):
        """Should I sign up to accept incoming data?."""
```
What's going on?

**Comment by Arcanemagus** [comment]
D211 is meant to replace D203, and in fact D203 doesn't show up when `pep257` is called directly, but with the way `pylama` (and other "aggregators") call it, both show up.

I would recommend adding `D203` to your list of ignored error codes :wink:.

**Comment by bemeurer** [comment]
@Arcanemagus Makes much more sense now! I added `D203` to my ignored codes and it's working like a charm again. Thanks for the help and for the awesome plugin!

**Comment by gmist** [comment]
It happens because pep257 adds D203 to the list of ignored warnings [by default](https://github.com/PyCQA/pydocstyle/blob/master/src/pydocstyle.py#L706). In Pylama pep257 runs as ```pep257 --ignore 'your_list_of_warnings' some_file.py```, so Arcanemagus gave the right advice.

**Comment by Arcanemagus** [comment]
Ah, didn't know _why_ it didn't get that by default, good to know :wink:.
