### ISSUE TITLE
Error finding pylama executable

### ISSUE THREAD

**Issue by jonobacon** [AtomLinter/linter-pylama#33]
Hi Everyone,

I am using Atom 1.6.0 and installed `linter-pylama`. Upon enabling the package I didn't have `pylama` installed so I installed it with `pip`.

Then disabled the package and re-enabled it and I keep getting this error:

<img width="475" alt="screen shot 2016-03-19 at 11 18 24 am" src="https://cloud.githubusercontent.com/assets/3004831/13900470/6267e2dc-edc4-11e5-8f15-255b8aeead70.png">

From what I can tell there is no-where to set the path, so I would consider this a bug.

My executable according to `which` is in `/usr/local/bin/pylama` and I can run `pylama` manually on a Python file and it works.

Thanks!

**Comment by Arcanemagus** [comment]
What does your settings screen look like? You should have an `Executable Path` setting that would allow you to overrule the automatic detection (which should be working, but that is another story).

**Comment by jonobacon** [comment]
@Arcanemagus do you mean the settings screen for linter-pylama? If so, I see no settings screen (at least no `Executable Path` box.

Or, do you mean the general Atom settings? I don't see an `Executable Path` there either.

**Comment by Arcanemagus** [comment]
Under Packages -> Linter Pylama you should see a screen similar to this:
![image](https://cloud.githubusercontent.com/assets/427137/13932265/78171476-ef64-11e5-8bb9-8795144b63ea.png)

**Comment by jonobacon** [comment]
Weird, I don't see that. I see this:

<img width="1066" alt="screen shot 2016-03-21 at 12 59 16 pm" src="https://cloud.githubusercontent.com/assets/3004831/13932336/cf31c3d2-ef64-11e5-9c7a-40a9a32057a3.png">

**Comment by Arcanemagus** [comment]
That's a bug with Atom's settings view, I'm not sure on the exact fix, have you tried uninstalling the package and re-installing it?

**Comment by jonobacon** [comment]
Strange. I reinstalled the package and now it works.

It would be helpful to let the Atom team know about this - if you know what this bug is, do you know if it has been filed?

**Comment by Arcanemagus** [comment]
Actually I always assumed it was filed, but I can't find it from a few quick searches, this was the only related one I found: https://github.com/atom/atom/issues/10426

**Comment by jonobacon** [comment]
I will comment on that issue and reference this issue. Thanks!

**Comment by Arcanemagus** [comment]
Marking this as closed btw, unless there was something else?

**Comment by JohnRobson** [comment]
Atom give error: "Provided path doesn't exist.  pylama  Please fix pylama path or install latest version."

I reinstalled: linter-pylama, linter-python, linter-pylint

And I have installed on Archlinux:
$ pylama --version
pylama 7.3.3
$ pylint --version
No config file found, using default configuration
pylint 1.7.1, 
astroid 1.5.2
Python 3.6.1 (default, Mar 27 2017, 00:27:06) 
[GCC 6.3.1 20170306]

Still not finding this path.

**Comment by gmist** [comment]
@JohnRobson, please try to specify the full path to executable files (/usr/local/bin/pylama, /opt/bin/python etc)

**Comment by JohnRobson** [comment]
@gmist thank you, I solved by installing pylama pylama_pylint packages
