### ISSUE TITLE
Pylama and Pylint warning

### ISSUE THREAD

**Issue by erdemalpkaya** [AtomLinter/linter-pylama#35]
<img width="1440" alt="screen shot 2016-05-05 at 11 04 20 am" src="https://cloud.githubusercontent.com/assets/18541694/15031978/31eb1540-12b1-11e6-9ced-2cec51edc13b.png">

I had this problem but Atom python was working before, then I downloaded python 3x version and I install - uninstall some of Atom packages I got this warning which when I open python folder it is displayed on my Atom interface

<img width="1440" alt="screen shot 2016-05-05 at 12 16 42 am" src="https://cloud.githubusercontent.com/assets/18541694/15032041/a2697cc6-12b1-11e6-9cd6-a991c82b56ec.png">

so I don't know what happen! Anyone knows?
I really need help I can't turn on python folder!

<img width="1440" alt="screen shot 2016-05-05 at 12 30 05 am" src="https://cloud.githubusercontent.com/assets/18541694/15032131/1fb762f6-12b2-11e6-9b36-c2dcd8821def.png">

**Comment by Arcanemagus** [comment]
Marking this as closed since you have reported the _exact_ same thing over in https://github.com/AtomLinter/linter-pylint/issues/142 there is no point in discussing it in two different places.
