### ISSUE TITLE
Virtual environment?

### ISSUE THREAD

**Issue by dpo** [AtomLinter/linter-pylama#38]
How does this package work in conjunction with a virtual environment? I constantly get PyLint errors that such and such module can't be imported. Because the module in question resides in a virtual environment, as does my project, it's looking like the wrong interpreter is being used.

It seems that if I launch Atom from the command line while the virtualenv is activated, the issue goes away, but that's quite inconvenient.

Is there a way to specify what interpreter should be used? Perhaps something using `PROJECT_NAME`, as in `autocomplete-python`?!

Thanks.

**Comment by gmist** [comment]
That's right if you launch Atom from the command line then is possible to [detect](https://github.com/AtomLinter/linter-pylama/blob/master/bin/pylama.py#L12) environment variables and discover a virtual environment.

**Comment by ddaanet** [comment]
My current solution is just to install pylama and friends into the virtualenv, and then configure linter-pylama to use the bin/pylama in the venv.

It would really be nice if the external pylama would default to ${PROJECT_PATH}/venv/bin/pylama, or something similar, in the same way that autocomplete-python finds a virtualenv in the project root.
