### ISSUE TITLE
Unable to use linter-pylama on Windows

### ISSUE THREAD

**Issue by curinir** [AtomLinter/linter-pylama#4]
There are a couple of issues:
1) When using an external linter, when calling "pylama.exe --version", the output is for example: "pylama.exe 6.2.0". Since linter-pylama looks for "pylama {VERSION}", this fails because of the .exe.

2) The output from pylama will have Windows-style newlines. This means that the linter regex should end with something like '(\r)?\n' instead of just '\n'. Otherwise the matcher doesn't work correctly.

**Comment by gmist** [comment]
It seems to be fixed. Thanks!
