### ISSUE TITLE
Shows no errors

### ISSUE THREAD

**Issue by Worldrider** [AtomLinter/linter-pylama#41]
ubuntu 14.04, atom 1.8.0,  linter-pylama 0.5.1, linter 1.11.14, pylama 7.0.9.

Linter stopped showing any errors in atom, while pylama works if launch manually from terminal.
It began from 0.2.8 version or near that and until now.
From that time I keep updating linter-pylama on every release but no result.

Tried reinstalling atom (with all settings and packages), reinstalling pylama, pylama_pylint, pylint itself - nothing helped. Both for internal and external settings.

Atom console says:
"/home/eugene/.atom/packages/linter-pylama/lib/init.coffee:74 Linter-Pylama: package loaded, ready to get initialized by AtomLinter."
Please help me to make it work or fix it - I'm out of ideas on it.

**Comment by Worldrider** [comment]
Thank you for such fast reaction in issue, but it didn't work for me =/
Also I found that same problem is with linter-pylint - pylint works from terminal, but linter-pylint does not initialize in atom. Meanwhile linter-pep8 works. Seems like I'm the only one who has such problem, so sorry for bothering you.

**Comment by gmist** [comment]
unfortunately I was not able to reproduce it
![virtualbox_ubuntu1404_20_07_2016_13_45_19](https://cloud.githubusercontent.com/assets/47926/16983982/dab0d26a-4e88-11e6-95ce-aed184b33027.png)

**Comment by Arcanemagus** [comment]
@Worldrider can you close _all_ Atom windows, then launch Atom with `atom .` from a terminal window where the commands are working from?

**Comment by Worldrider** [comment]
@gmist Thank you for trying - I think it's a good sign
@Arcanemagus what else can I do to provide more information? 
![image](https://cloud.githubusercontent.com/assets/12088053/17000786/e628fcc8-4ecc-11e6-9c36-27d6fd153a2c.png)
![image](https://cloud.githubusercontent.com/assets/12088053/17000805/f5669308-4ecc-11e6-9595-b81034ca77e3.png)

**Comment by Worldrider** [comment]
![image](https://cloud.githubusercontent.com/assets/12088053/17001107/54ff94e4-4ece-11e6-984c-bdecfcffaab2.png)
![image](https://cloud.githubusercontent.com/assets/12088053/17001115/679881ce-4ece-11e6-97e3-e621edc91e49.png)

**Comment by Arcanemagus** [comment]
Uh, you shouldn't be launching Atom through `sudo` 😮.

**Comment by Arcanemagus** [comment]
Okay, in your Atom window it shows the language as `Python Django` in the lower right corner, what do you get if you run `Editor: Log Cursor Scopes` from the Command Palette?

**Comment by Worldrider** [comment]
@Arcanemagus  it didn't lauch without sudo

**Comment by Worldrider** [comment]
![image](https://cloud.githubusercontent.com/assets/12088053/17001229/d72350aa-4ece-11e6-8e45-01b8115bb23e.png)

**Comment by gmist** [comment]
[oops](https://github.com/AtomLinter/linter-pylama/blob/master/lib/init.coffee#L78)

**Comment by Worldrider** [comment]
@gmist  that's it? :)

**Comment by Arcanemagus** [comment]
Assuming Django code is 100% perfectly valid Python, it should be as simple as adding `source.python.django` to that list.

**Comment by Worldrider** [comment]
@Arcanemagus 2 minutes

**Comment by Worldrider** [comment]
@gmist  @Arcanemagus  Yeeah! Thank you a lot - that worked! ))

**Comment by gmist** [comment]
@Arcanemagus tanks you!

**Comment by Worldrider** [comment]
@gmist still works after update :+1:
