### ISSUE TITLE
Separate counter for warnings and errors

### ISSUE THREAD

**Issue by luciengaitskell** [AtomLinter/linter-pylama#46]
Both the _Errors_ and the _Warnings_ are counted together and colored red, which is deceiving. Is it possible to add an option to display separate counters?

**Comment by Arcanemagus** [comment]
This package has nothing to do with the UI, you would want to file that over on [linter-ui-default](https://github.com/steelbrain/linter-ui-default/issues) where work on the new linter UI is being done.
