### ISSUE TITLE
Fails to ignore D203

### ISSUE THREAD

**Issue by adamboche** [AtomLinter/linter-pylama#51]
I've written `D203` into "Ignore Errors and Warnings" but it doesn't ignore instances of D203. It does ignore all the other codes I've put in there. 

Screenshot: http://imgur.com/a/6xqDY

linter-pylama 0.7.0
Atom 1.10.2

**Comment by gmist** [comment]
Try to remove spaces: D102,D103,D203,C0111,R0201,W0401
