### ISSUE TITLE
isort support

### ISSUE THREAD

**Issue by cemsbr** [AtomLinter/linter-pylama#53]
If isort is specified in setup.cfg, for example, atom gives an annoying warning 'WARNING:root:Linter isort not found.' every time.

**Comment by Arcanemagus** [comment]
Does it work on the CLI?

**Comment by gmist** [comment]
At the moment the internal Pylama does not support ```isort```.

**Comment by cemsbr** [comment]
Yes, it works on the CLI and I'm using internal pylama.
