### ISSUE TITLE
Pylama was not found

### ISSUE THREAD

**Issue by Hessmjr** [AtomLinter/linter-pylama#6]
Trying to utilize pylama linter on Atom and not having any luck.  I keep getting error binary pylama not found.  Can you possibly assist?

**Comment by gmist** [comment]
What version of OS are you using?

**Comment by Hessmjr** [comment]
Sorry didn't leave more details: Atom 1.0
MacBook Pro Retina - OSX V10.10.3

**Comment by gmist** [comment]
Hmm... interesting. You could give me a little more information about your environment? Please execute the following commands in your terminal:
```
apm list --packages
```
```
which python
```
```
python --version
```

and if you use an external Pylama
```
which pylama
```
```
pylama --version
```

**Comment by Hessmjr** [comment]
Here are the packages I've added to the already built-in:
├── color-picker@2.0.7
├── linter@1.1.0
├── linter-csslint@0.0.14
├── linter-erb@0.1.1
├── linter-htmlhint@0.0.16
├── linter-javac@0.1.4
├── linter-jshint@0.1.7
├── linter-pylama@0.0.20
└── minimap@4.10.1

Which python:
/usr/bin/python

Python version:
Python 2.7.6

I don't use an external Pylama.  Is that required?  My understanding of this package is its self-containing other than Linter.

**Comment by gmist** [comment]
Unfortunately, I could not reproduce this problem on any of my computers. Try to remove the package and reinstall it after restart Atom. You can also check the availability and access rights to pylama.py
```ls -al ~/.atom/packages/linter-pylama/bin```
```~/.atom/packages/linter-pylama/bin/pylama.py --version```
![screen shot 2015-07-02 at 18 56 16](https://cloud.githubusercontent.com/assets/47926/8481608/ab1ba9dc-20ec-11e5-94c8-ec8b917b452c.png)

**Comment by Hessmjr** [comment]
This is what I was able to get from running the scripts you mentioned:

![screen shot 2015-07-02 at 12 07 04 pm](https://cloud.githubusercontent.com/assets/7245108/8483067/8e8f42d0-20b3-11e5-8111-33095ef3628c.png)

**Comment by Hessmjr** [comment]
I uninstalled and reinstalled again to test.  I have Pylint not selected since I'm not using external Pylama and I have internal pylama selected obviously.  I can't tell if it is doing anything though, is there a good way to test?

**Comment by gmist** [comment]
At the moment all debug information is disabled. I have created a [special branch](https://github.com/AtomLinter/linter-pylama/tree/debug_info) which added debug messages. You can use it to find the place of occurrence a problem:
``` shell
git clone -b debug_info https://github.com/AtomLinter/linter-pylama.git
```
``` shell
cp linter-pylama/lib/linter-pylama.coffee ~/.atom/packages/linter-pylama/lib
```
and restart Atom if it is running. Then, when you open python file, press Command+Option+i to enable Developer Tools:
![screen shot 2015-07-02 at 23 02 04](https://cloud.githubusercontent.com/assets/47926/8486937/33ea9c90-2111-11e5-90f8-eb071617e407.png)

**Comment by gmist** [comment]
Is it still relevant after last update?

**Comment by Hessmjr** [comment]
Unfortunately I have uninstalled the package and tried a different route with my Python linting, thank you for following up.  I will close the issue.

**Comment by JohnRobson** [comment]
Atom give error: "Provided path doesn't exist.  pylama  Please fix pylama path or install latest version."

I reinstalled: linter-pylama, linter-python, linter-pylint

And I have installed on Archlinux:
$ pylama --version
pylama 7.3.3
$ pylint --version
No config file found, using default configuration
pylint 1.7.1, 
astroid 1.5.2
Python 3.6.1 (default, Mar 27 2017, 00:27:06) 
[GCC 6.3.1 20170306]

Still not finding this path.

**Comment by abhi-jha** [comment]
Did anybody find a solution?

**Comment by gmist** [comment]
@abhi-jha  do you have installed ```linter-python``` package?

**Comment by abhi-jha** [comment]
pylama --version
pylama 7.4.3

**Comment by gmist** [comment]
```apm list | grep linter``` ?

**Comment by abhi-jha** [comment]
├── linter@2.2.0
├── linter-pylama@0.9.5
├── linter-python@3.1.2
├── linter-ui-default@1.7.1

**Comment by gmist** [comment]
@abhi-jha try to remove linter-python

```app remove linter-python```
