### ISSUE TITLE
Error found pylama

### ISSUE THREAD

**Issue by tubipham** [AtomLinter/linter-pylama#62]
![screen shot 2017-03-03 at 13 37 46](https://cloud.githubusercontent.com/assets/4744234/23540893/9c3e5cf6-0016-11e7-9a73-19e93fe70b2f.png)

i using pylama version 7.3.3. atom 1.14
I always receive this error, though i uninstalled and reinstalled pylama

**Comment by ddaanet** [comment]
PR #74

**Comment by ddaanet** [comment]
@tubipham Do you still have this problem with linter-pylama 0.8.19?
