### ISSUE TITLE
Recognizes Python 3.5's async function definitions as incorrect syntax

### ISSUE THREAD

**Issue by ErikBoesen** [AtomLinter/linter-pylama#64]
Example case:

```py
async def run_together(self):
        """Do a thing while doing another thing."""
        for i in range(0, 10):
            print(i)
```

This will trigger an E0100 SyntaxError: Invalid syntax.

Is this a pylama issue or something that can be fixed here?

**Comment by Arcanemagus** [comment]
This is mainly just a wrapper around `pylama`, do you get the same results when running `pylama` on the CLI?

**Comment by gmist** [comment]
Probably you are using Python 2.x by default
``` shell
$ python --version
> Python 2.7.13
```
<img width="125" alt="screen shot 2017-03-21 at 18 54 02" src="https://cloud.githubusercontent.com/assets/47926/24157152/9a737472-0e69-11e7-915a-d71dd04e1f33.png">

Go to the package settings and specify Python version
<img width="150" alt="screen shot 2017-03-21 at 18 54 29" src="https://cloud.githubusercontent.com/assets/47926/24157159/a4d2ce54-0e69-11e7-988f-c415fc6ce59b.png">

<img width="160" alt="screen shot 2017-03-21 at 18 57 16" src="https://cloud.githubusercontent.com/assets/47926/24157168/ac4094b4-0e69-11e7-9c24-c10c140bbd06.png">

**Comment by ErikBoesen** [comment]
That was the issue. Thank you!
