### ISSUE TITLE
Isort

### ISSUE THREAD

**Issue by ghost** [AtomLinter/linter-pylama#68]
Really love the Isort function but for some reason I need to press it several times, change the cursor position etc. and only once every 20-30 tries does it actually sort.  Unless there is some requisites on when it works?

Many thanks!

**Comment by Arcanemagus** [comment]
If you enable the ["Use isort" option](https://github.com/AtomLinter/linter-pylama/blob/e3365f8415ac6e73df275e07fee06ee84608cf84/lib/init.coffee#L93), this should be done whenever a regular lint is triggered, is that what you were looking for?

**Comment by ddaanet** [comment]
I think the reported problem relates to automatic isort on save, it refers to "it actually sorts".

My guess would be some timing sensitive interaction with another atom.io package on file save.

**Comment by JGH1000** [comment]
Think the problem was with the isort command from the console (Ctrl+Alt+Shift+I) as I have the same problem. However, it seems that this happens when file was modified and not saved. 

After saving the file isort command works every time, on a modified file it never does. I am not sure if this is indented but it can be frustrating for someone who has not noticed that.

**Comment by ddaanet** [comment]
Oh right, I have observed that too, but I have worked around it before it actually reached my conscious mind. That should be a different, more specific bug though.

**Comment by JGH1000** [comment]
@ddaanet the OP closed his account, should we close this and reopen a new one for the isort fail on modified files or just leave as is?

**Comment by ddaanet** [comment]
@JGH1000 I am doing just that, right now.

**Comment by ddaanet** [comment]
Ahem, except I am not allowed to close bugs in this project. Yet?

**Comment by JGH1000** [comment]
@ddaanet thanks, I will leave it with you then. Happy to see the linter is actively maintained, it is incredibly useful.

**Comment by ddaanet** [comment]
#75

**Comment by JGH1000** [comment]
Moderator please close.

thanks @ddaanet
