### ISSUE TITLE
unreasonable for large files

### ISSUE THREAD

**Issue by razvanc87** [AtomLinter/linter-pylama#7]
Hi. So first off, thanks for the plugin and good job! Now the hard part: how difficult do you think it would be to implement an option in the settings to let the user pick between check on the fly and check only at save... because although useful, it is super annoying when working with large files and everything becomes slow... what do you think about the proposal? Thanks!

**Comment by k2b6s9j** [comment]
How many lines is a 'large' file?

**Comment by razvanc87** [comment]
Actually... now I'm not sure if it's a problem with the base linter or with this particular plugin or even `atom` itself... because in a file with many warnings/errors, scrolling with the keyboard is very slow, but don't know for sure if this is because the check is real-time... don't know how to exactly check this, but I'm inclined to think that real-time checking has a major impact on performance. I'm talking about files of 170 lines with quite a few warnings/errors... so really it's not even a big file. (I just opened the `crom.py` file from the `ipykernel` module to check this).

**Comment by gmist** [comment]
I think it will be possible after migration to a new version of the Linter package.
