### ISSUE TITLE
Pyflakes settings checkbox uncheck itself.

### ISSUE THREAD

**Issue by niksite** [AtomLinter/linter-pylama#71]
Hi,

Today I notice that pyflakes stop working, so I check settings and found pyflakes unchecked. 
When I check it again and restart Atom I found it back in unchecked state. If I do not restart Atom, it seems to be working.

Is there anything I could do to prevent such pyflakes auto-disabling?

**Comment by Arcanemagus** [comment]
Are you using `project-manager`? Nothing in this package changes it's own settings.

**Comment by Arcanemagus** [comment]
Turns out I was mistaken, if you enable the "Use Radon" setting it will automatically disable "Use McCabe" and "Use Pyflakes". Are you enabling that option?

**Comment by niksite** [comment]
Yes, it was Radon. It's a bit confusing - if you enable Pyflakes it will not disable Radon, they will both be enabled for a while. And Radon immediately disable McCabe but it disable Pyflakes only after some time (or event?).

**Comment by Arcanemagus** [comment]
What version of Atom are you on?

* Enabling Pyflakes should [disable Radon](https://github.com/AtomLinter/linter-pylama/blob/v0.8.16/lib/linter-pylama.coffee#L70).
* Enabling Radon should [disable Pyflakes](https://github.com/AtomLinter/linter-pylama/blob/v0.8.16/lib/linter-pylama.coffee#L80-L81) at the same time it disables McCabe.

**Comment by niksite** [comment]
1.16.0

> Enabling Radon should disable Pyflakes at the same time it disables McCabe.

Confirmed.

> Enabling Pyflakes should disable Radon.

Not confirmed:
<img width="288" alt="screen shot 2017-04-28 at 1 23 26 pm" src="https://cloud.githubusercontent.com/assets/99423/25546016/f7058d3c-2c15-11e7-9da7-a07b5c3d0e96.png">
