### ISSUE TITLE
"BASH_FUNC_module" sh: scl: riga 1

### ISSUE THREAD

**Issue by francescomeloni** [AtomLinter/linter-pylama#72]
I am sorry but i don't know hot to name this issue. 
every time i edit the file this notification appeared. 
All was fine until the yesterday update. 

> sh: module: riga 1: errore di sintassi: EOF non atteso sh: errore nell'importazione della definizione di funzione per "BASH_FUNC_module" sh: scl: riga 1: errore di sintassi: EOF non atteso sh: errore nell'importazione della definizione di funzione per "BASH_FUNC_

thanks 
F.

**Comment by ddaanet** [comment]
It would be nice if you could set your system locale to english and reproduce the error. Not everybody can read italian error messages.

**Comment by francescomeloni** [comment]
`sh: module: line 1: syntax error: unexpected end of file sh: error importing function definition for BASH_FUNC_module' sh: scl: line 1: syntax error: unexpected end of file sh: error importing function definition forBASH_FUNC_scl'`

**Comment by ddaanet** [comment]
I cannot see how linter-pylama could be the source of the error.

More probably, there is something very wonky going on with your shell environment. Google for BASH_FUNC_scl, you will find many other bug reports from people having a similar problem.

**Comment by francescomeloni** [comment]
thanks, 
digging i found that it is a fedora related bug 
I removed the package environment-modules and things started working again. Apparently this messes up the bash environment in some way I don't understand.
