### ISSUE TITLE
Error Pylama

### ISSUE THREAD

**Issue by RobotXP** [AtomLinter/linter-pylama#73]
Hello,

Currently with Atom 1.6.0 installed, I decided to install the linter-pylama package and I get this message whenever I type anything ....

http://ap.imagensbrasil.org/image/jNeyw6

I have tried to uninstall linter-pylama and Atom and reinstall, but it does not work, I tried to install another linter, but it also does not work, what do I do?

**Comment by ddaanet** [comment]
I guess you are having the same problem I have with external pylama. PR #74

**Comment by ddaanet** [comment]
Duplicate of #62

**Comment by ddaanet** [comment]
@RobotXP do you still have this problem with `linter-pylama` 0.8.19?
