### ISSUE TITLE
Unknown Error Message Spam

### ISSUE THREAD

**Issue by JGH1000** [AtomLinter/linter-pylama#76]
Every couple of minutes or so I get several consecutive error messages saying to check the developer tool. There I got 40-50 of the first message below and 2 of the second message:

[Linter] Error running Unknown Error: Process execution timed out(…)(anonymous function) @ /home/usr/.atom/packages/linter/lib/linter-registry.js:159

[Linter] Error running Unknown Error: Process execution timed out(…)(anonymous function) @ linter-registry.js [sm]:137

I tried removing and reinstalling linter-based packages, disabling all other linter-related extension but nothing really helped. Only disabling linter-pylama solved the issue. I am running the newest Atom release and all packages are up to date.

I am also running the internal linter version as the external cannot find pylint (even though I installed pylama-pylint).

Many thanks for looking into this.

**Comment by gmist** [comment]
Unfortunately I could not reproduce this error.

**Comment by JGH1000** [comment]
Guess for some reason I am the only one affected. Switched to linter-python so will close this issue. Thanks for looking into this!

**Comment by kylefelipe** [comment]
Hi... im new on atom and i have the same issue.....
