### ISSUE TITLE
PyLama plugin is broken in Atom 1.19beta0: 'TypeError: Cannot read property '17' of undefined'

### ISSUE THREAD

**Issue by vrutkovs** [AtomLinter/linter-pylama#79]
OS: Fedora 25
Atom: 1.19.0-beta0 (built in Flatpak)
Electron: 1.6.9
Chrome: 56.0.2924.87
Node: 7.4.0
Python: 3.5.2
pylama: 7.3.3

Whenever I open a python file I get an error in console:
```
[Linter] Error running Pylama TypeError: Cannot read property '17' of undefined
    at /home/vrutkovs/.atom/packages/linter-pylama/lib/helpers.coffee:110:46
    at Array.map (native)
    at /home/vrutkovs/.atom/packages/linter-pylama/lib/helpers.coffee:96:38
(anonymous) @ /home/vrutkovs/.atom/packages/linter/lib/linter-registry.js:159
```

This might be related to a full rewrite of editor in 1.19 - as otherwise pylama works perfectly in 1.18

**Comment by Arcanemagus** [comment]
Wow, looks like somebody was using the internal state of the `TextEditor` instead of the public API, no wonder it broke.
