### ISSUE TITLE
Including mypy linter

### ISSUE THREAD

**Issue by JGH1000** [AtomLinter/linter-pylama#83]
I realize that mypy is not part of pylama but neither is isort so I thought I would ask - any chance of including this linter as an option? Quite useful!

**Comment by JGH1000** [comment]
Probably not popular enough, thanks anyway!

**Comment by gmist** [comment]
You can try [linter-mypy](https://atom.io/packages/linter-mypy)

**Comment by JGH1000** [comment]
Yep, just found it. Thanks!
