### ISSUE TITLE
Provided path doesn't exist.

### ISSUE THREAD

**Issue by slipy-spy** [AtomLinter/linter-pylama#84]
-------------------------------------------------------
Provided path doesn't exist.

pylama

Please fix pylama path or install latest version.

----------------------------------------------------------

when i use Atom for Python with linter-pylama, i have this problem

**Comment by Arcanemagus** [comment]
Have you installed `pylama` on your system?

**Comment by gmist** [comment]
Try to remove ```linter-python``` plugin if it is installed. It's very similar to #78

**Comment by Runinterface** [comment]
Add linter-python, a direct path to the pylama, in the configuration.
my path / usr/local/bin/pylama
<img width="776" alt="2017-10-23 14 42 38" src="https://user-images.githubusercontent.com/5904645/31887305-75632c22-b800-11e7-8fab-089a1ef5840a.png">

**Comment by Arcanemagus** [comment]
@Runinterface This is `linter-pylama`, if you are having issues with `linter-python` you should file an issue over there.

Closing due to a lack of response from @slipy-spy. If you are still having problems (and are actually using `linter-pylama` 😛) feel free to respond!

**Comment by damianobarbati** [comment]
@slipy-spy did you manage to solve this? I have pylama at `/usr/local/bin/pylama` which is the default location but linter-pylama does not find either way: not if I leave the default path, neither if I set it (uselessly?) manually to `/usr/local/bin/pylama`.

Funny error message:
```
Provided path doesn't exist.
/usr/local/bin/pylama
Please fix pylama path or install latest version
```
Double check in console:
```
imac:core damz$ which pylama
/usr/local/bin/pylama
```
